### ISSUE TITLE
pkgdown code not copyable 

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/amadeus#99]
## Code in deployment should be copyable

The source code readme (https://github.com/NIEHS/amadeus/) is copyable. For example the line 

```
pak::pak("NIEHS/amadeus")
```

can be copied for ease of implementation. However, the pkgdown deployment is not at https://niehs.github.io/amadeus/

Maybe this is standard, but it would be nice.

**Comment by sigmafelix** [comment]
I found all code blocks in README.md were generic (i.e. starting with "\`\`\`" not "\`\`\`r"). It might be related to the problem. I will check it somewhere else and make a PR to Mitchell's branch with my changes that were pushed after the last PR.

**Comment by mitchellmanware** [comment]
I think this happened as a result of not wanting to run the download chunks in the building of the package which runs the README.md file. I can fix these

**Comment by sigmafelix** [comment]
I think the issue is in the pkgdown page. The current `amadeus` webpage displays code blocks without copy-and-paste functionality: https://niehs.github.io/amadeus

<img width="904" alt="image" src="https://github.com/NIEHS/amadeus/assets/25448786/2546be01-e77d-4a0c-ae4b-0f4d73f04be7">

In contrast, all code blocks in `beethoven` webpage have the functionality (to note, copy buttons show up upon hovering the cursor on a code block): (https://niehs.github.io/beethoven) The difference between README.md source of `amadeus` and that of `beethoven` is that the backtick symbols are followed by "r" or nothing.

<img width="904" alt="image" src="https://github.com/NIEHS/amadeus/assets/25448786/b856ef01-a795-465a-911c-7b7cd9bd2867">

https://github.com/NIEHS/beethoven/blob/9e4daf19e69c2a099f5b9471da96ce2a3c5cd942/README.md?plain=1#L9-L20

My quick experiment in one of my repos shows this. https://sigmafelix.github.io/speed/

**Comment by mitchellmanware** [comment]
@sigmafelix Ahh, yes I see.

`r` has been added to code blocks with code but not output (https://github.com/NIEHS/amadeus/commit/2967113fe6f8659a25431fd2fc18b8d81e01f3e5).
